name: Comment on Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  comment:
    runs-on: ubuntu-latest  

    permissions:
      pull-requests: write

    steps:
      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: "comment"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
