name: Comment on Pull Request

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Determine comment type
        id: set-comment
        run: |
          if [[ "$GITHUB_HEAD_REF" == *frontend* ]] || [[ "$GITHUB_HEAD_REF" == fe/* ]]; then
            echo "message=🚀 Thanks for the frontend changes! Please ensure UI tests pass and components are responsive." >> $GITHUB_OUTPUT
          elif [[ "$GITHUB_HEAD_REF" == *backend* ]] || [[ "$GITHUB_HEAD_REF" == be/* ]]; then
            echo "message=🔧 Thanks for the backend changes! Remember to update API docs and check database migrations." >> $GITHUB_OUTPUT
          else
            echo "message=📌 Thank you for your contribution! Please ensure all checks pass before merging." >> $GITHUB_OUTPUT
          fi

      - name: Comment on PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: ${{ steps.set-comment.outputs.message }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
